#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

'''
Yes, there is a difference in the data type of the variables list_ and array_list.
list_ is a Python list object, while array_list is a NumPy array object.
'''

<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [5]:
for x in list_:
    print(type(x))
    
for y in array_list:
    print(type(y))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3 Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [6]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

'''
The dtype parameter is used to specify the data type of the elements in the NumPy array. In this case, we are setting the dtype 
to int, which means that the elements in array_list will be of type int, whereas the elements in list_ are of type str.
'''
for x in list_:
    print(type(x))
    
for y in array_list:
    print(type(y))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(num_array.shape)
print(num_array.size)

(2, 3)
6


#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. 

In [13]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [15]:
arr1 = np.eye(5)
print(arr1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
